package SDET_DATADRIVEN;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

// Code for data driven test by hardcode the data in our code


public class DataDrivenTest {

	
	WebDriver driver;
	
	@SuppressWarnings("deprecation")
	@BeforeClass
	public void setup()
	{
        System.setProperty("webdriver.chrome.driver", "E:\\seleniumfiles\\chromedriver_win32\\chromedriver.exe");
		
	    driver = new ChromeDriver();  // creating chrome browser driver in web driver interface
	    
	    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		driver.manage().window().maximize();     // maximize the browser window 
		
	}
	
	
	

	  // This method runs with multiple sets of test data and that data generated by a @DataProvider annotation method
	
	@Test(dataProvider="LoginData")

	public void loginTest(String user, String pwd, String exp)       // exp is used to check data us valid or not   
	{
		driver.get("https://admin-demo.nopcommerce.com/login/");
		
		WebElement txtEmail = driver.findElement(By.id("Email"));
		txtEmail.clear();
		txtEmail.sendKeys(user);    // this user name value is coming from a Data provider annotation method
		
		WebElement txtPassword = driver.findElement(By.id("Password"));
		txtPassword.clear();
		txtPassword.sendKeys(pwd);      // this pwd value coming from a Data Provider annotation method
		
		driver.findElement(By.xpath("//button[@type='submit']")).click();   // clicking on login button
		
		
		String exp_title = "Dashboard / nopCommerce administration";  // expected title after login, we get this from developer
		
		String act_title = driver.getTitle();   // actual title
		
		
		
		// Here we cover scenario of positive as well as negative testing both
		
		if(exp.equals("Valid"))          // This if condition code is for positive testing means for valid data
		{
			if(exp_title.equals(act_title))     // to check login is successful or not
			{
				driver.findElement(By.linkText("Logout")).click();
				Assert.assertTrue(true);      // This test case passed means our login successful
				
			}
			
			else
			{
				Assert.assertTrue(false);  // here we fail test case intentionally 
				
			}
			
			
		}
		
		
		else if(exp.equals("Invalid"))          // This if condition code is for negative testing means for Invalid data
		{
			if(exp_title.equals(act_title))  // to check login is successful or not
			{
				driver.findElement(By.linkText("Logout")).click();
				Assert.assertTrue(false);    // here we fail my test case because we pass here invalid data
				
			}
			
			else
			{
				Assert.assertTrue(true);
				
			}
			
		}
		         
		
		
		
		
	}
	
	
	

	

	
	
	
	
	// Data Provider annotation provide data to another test method
	
	// Now we create a data provider method, Data provider method always returns a 2D array, so we take return type String[][] in 2d format
	
	// Here data is only string so we use return type as a String[][], if data is present in string as well as in number format so then use return type as Object[][]
	
	
	
	@DataProvider(name="LoginData")
	public String[][] getData()   // Here first we are going to hardcode the data and provide this data to our test case
	{

		// Here data defined is in string so we make a 2D array with string type
		
		String loginData[][] =
			{
					{"admin@yourstore.com","admin","Valid"},  // here we kept data in 2d array
					{"admin@yourstore.com","adm","Invalid"},
					{"adm@yourstore.com","admin","Invalid"},
					{"adm@yourstore.com","adm","Invalid"}
					
					
			};
		
		
		return loginData;
		
	}
	
	
	
	
	@AfterClass
	void tearDown()
	{
		driver.close();
		
	}
}
